#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Arrêt en cas d'erreur
set -e

# Format et lint
echo "🎨 Formatting..."
pnpm format || exit 1

echo "🔍 Linting..."
pnpm lint || exit 1

echo "🧪 Testing..."
pnpm test || exit 1

# Stage les fichiers modifiés
git add -A
