name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'fix/**'
      - 'hotfix/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      # Step 3: Install PNPM
      - name: Install PNPM
        run: corepack enable && corepack prepare pnpm@latest --activate

      # Step 4: Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Step 5: Run Linting
      - name: Lint code
        run: pnpm lint

      # Step 6: Run Unit Tests
      - name: Run tests
        run: pnpm test

      # Step 7: Upload Coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/*.json
          flags: unittests
          name: codecov-umbrella

  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Step 4: Build the package
      - name: Build package
        run: pnpm build

      # Step 5: Publish with Semantic Release
      - name: Release with Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
